# Generated by Django 4.1.7 on 2023-03-18 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank.district')),
            ],
        ),
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('dob', models.DateField(default=None)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('', ''), ('female', 'FEMALE'), ('male', 'MALE')], default='', max_length=6)),
                ('phone', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField(max_length=500)),
                ('account_type', models.CharField(max_length=8)),
                ('materials_required', models.CharField(max_length=20)),
                ('district', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bank.district')),
                ('place', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bank.place')),
            ],
        ),
    ]
